### ISSUE TITLE
Adding .toString() or .execute()

### ISSUE THREAD

**Issue by caleb-mabry** [outerbase/sdk#15]
# Problem
I've been using the SDK for a couple of days now and there are times where errors do not happen but things do not update in my database. I think it would be really helpful to have a `.toString()` method so that we can see what query the SDK is building and sending to the backend. 

# Proposed Solutions
## Change .query() to .execute()

The current implementation has people using `.query()` to execute the query and send the response to the backend.
```js
let { data } = await db
    .insert({ first_name: 'John', last_name: 'Doe', position: 'Developer', avatar: 0 })
    .into('person')
    .returning(['id'])
    .query();
```

The new potential approach would be: 
```js
let { data } = await db
    .insert({ first_name: 'John', last_name: 'Doe', position: 'Developer', avatar: 0 })
    .into('person')
    .returning(['id'])
    .execute();
```
If I didn't want to `.execute()` I should be able to `.toString()`.
```js
const sqlQuery = await db
    .insert({ first_name: 'John', last_name: 'Doe', position: 'Developer', avatar: 0 })
    .into('person')
    .returning(['id'])
    .toString();
```

I think this will also help the project be able to better debug and test functions in the future, as we will have a standardized way to test the output of queries.

### .toString() is also another object
```js
const sqlQuery = await db
    .insert({ first_name: 'John', last_name: 'Doe', position: 'Developer', avatar: 0 })
    .into('person')
    .returning(['id'])
    .toOuterbaseString();
```
This way we might be able to add `sqlQuery.execute()` or `sqlQuery.toString()`

# Additional context
I think this kind of approach might also want us to lean towards not requiring a connection string for our object. That way this can be used as a query builder and also an SDK to interact with Outerbases backend

**Comment by Brayden** [comment]
I like this proposal. I wonder if an alternative to consider could also be `.toSQL()`

**Comment by Brayden** [comment]
Proposal accepted is supporting `.toString` to produce a fully qualified SQL statement with parameters filled in:

```
.toString // -> `SELECT id, name, value FROM playing_with_neon WHERE id = 1`
```
